[project]
name = "garbage-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keras-cv>=0.9.0",
    "matplotlib>=3.10.3",
    "tensorflow==2.19.0",
    "ultralytics>=8.3.148",
]
